export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const DECK_LOADING = "DECK_LOADING";
export const GET_DECKS = "GET_DECKS";
export const GET_DECK = "GET_DECK";
export const ADD_DECK = "ADD_DECK";
export const DELETE_DECK = "DELETE_DECK";
export const CLEAR_DECK = "CLEAR_DECK";
export const DECK_EDIT = "DECK_EDIT";
export const STAY_FRESHER = "STAY_FRESHER";
export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const GET_FEEDBACK = "GETFEEDBACK";
export const FEEDBACK_LOADING = "FEEDBACK_LOADING";
export const DELETE_FEEDBACK = "DELETE_FEEDBACK";


